### ISSUE TITLE
MS COCO format

### ISSUE THREAD

**Issue by abushattal1** [Kazuhito00/YOLOX-Colaboratory-Training-Sample#1]
I am trying to convert from pascal VOC to COCO but it show me the following error that my image should be integer. any idea??
Number of xml files: 2675
Traceback (most recent call last):
  File "voc2coco/voc2coco.py", line 42, in get_filename_as_int
    return int(filename)
ValueError: invalid literal for int() with base 10: '11000000568658_jpg.rf.e84f5b4e20ba7065cfcdc0b1df1e8177'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voc2coco/voc2coco.py", line 160, in <module>
    convert(xml_files, args.json_file)
  File "voc2coco/voc2coco.py", line 91, in convert
    image_id = get_filename_as_int(filename)
  File "voc2coco/voc2coco.py", line 45, in get_filename_as_int
    (filename))
ValueError: Filename 11000000568658_jpg.rf.e84f5b4e20ba7065cfcdc0b1df1e8177 is supposed to be an integer.
Number of xml files: 996
Traceback (most recent call last):
  File "voc2coco/voc2coco.py", line 42, in get_filename_as_int
    return int(filename)
ValueError: invalid literal for int() with base 10: '11000000455228_jpg.rf.94eda45f93fa79a87a553738bd85dbbb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voc2coco/voc2coco.py", line 160, in <module>
    convert(xml_files, args.json_file)
  File "voc2coco/voc2coco.py", line 91, in convert
    image_id = get_filename_as_int(filename)
  File "voc2coco/voc2coco.py", line 45, in get_filename_as_int
    (filename))
ValueError: Filename 11000000455228_jpg.rf.94eda45f93fa79a87a553738bd85dbbb is supposed to be an integer.

**Comment by Kazuhito00** [comment]
"voc2coco.py" currently only supports integer filenames.
Please correct the file name or correct the code by referring to the following PR.
[voc2coco PR#2 Remove integer requirement](https://github.com/Tony607/voc2coco/pull/2)

**Comment by Petilia** [comment]
Hello!

Your code runs and is a good example for others to follow.

Now I'm trying to use my images for training and I get an error.

I would like to know what tool you use for markup and how to do the markup correctly.

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.

**Comment by ibrahim014** [comment]
Hi, I am trying to convert from pascal VOC to coco but getting the same error. Does anyone solve this problem?

Number of xml files: 2829
Traceback (most recent call last):
  File "voc2coco.py", line 44, in get_filename_as_int
    return int(filename)
ValueError: invalid literal for int() with base 10: 'Czech_000000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voc2coco.py", line 153, in <module>
    convert(xml_files, args.json_file)
  File "voc2coco.py", line 87, in convert
    image_id = get_filename_as_int(filename)
  File "voc2coco.py", line 46, in get_filename_as_int
    raise ValueError("Filename %s is supposed to be an integer." % (filename))
ValueError: Filename Czech_000000 is supposed to be an integer.
