### ISSUE TITLE
Errors while training with own data

### ISSUE THREAD

**Issue by joshfox10** [Kazuhito00/YOLOX-Colaboratory-Training-Sample#4]
Hello,

I seem to be having troubles training with my own data.  I've followed the directions perfectly and tried numerous things to no avail.  Here's the error that I'm getting during training:

/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2022-03-27 22:41:37 | INFO     | yolox.core.trainer:136 - Model Summary: Params: 0.90M, Gflops: 1.04
2022-03-27 22:41:42 | INFO     | yolox.core.trainer:307 - loading checkpoint for fine tuning
2022-03-27 22:41:43 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.0.weight in checkpoint is torch.Size([80, 64, 1, 1]), while shape of head.cls_preds.0.weight in model is torch.Size([4, 64, 1, 1]).
2022-03-27 22:41:43 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.0.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.0.bias in model is torch.Size([4]).
2022-03-27 22:41:43 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.1.weight in checkpoint is torch.Size([80, 64, 1, 1]), while shape of head.cls_preds.1.weight in model is torch.Size([4, 64, 1, 1]).
2022-03-27 22:41:43 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.1.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.1.bias in model is torch.Size([4]).
2022-03-27 22:41:43 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.2.weight in checkpoint is torch.Size([80, 64, 1, 1]), while shape of head.cls_preds.2.weight in model is torch.Size([4, 64, 1, 1]).
2022-03-27 22:41:43 | WARNING  | yolox.utils.checkpoint:26 - Shape of head.cls_preds.2.bias in checkpoint is torch.Size([80]), while shape of head.cls_preds.2.bias in model is torch.Size([4]).
2022-03-27 22:41:43 | INFO     | yolox.data.datasets.coco:64 - loading annotations into memory...
2022-03-27 22:41:43 | INFO     | yolox.data.datasets.coco:64 - Done (t=0.00s)
2022-03-27 22:41:43 | INFO     | pycocotools.coco:88 - creating index...
2022-03-27 22:41:43 | INFO     | pycocotools.coco:88 - index created!
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
2022-03-27 22:41:43 | INFO     | yolox.core.trainer:154 - init prefetcher, this might take one minute or less...
2022-03-27 22:41:43 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (1262), thread 'MainThread' (140351630342016):
Traceback (most recent call last):

  File "train.py", line 139, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, cache=False, ckpt='yolox_nano.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='nano.py...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "/content/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fa626e3e7a0>

  File "train.py", line 117, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7fa51d270710>
    └ <yolox.core.trainer.Trainer object at 0x7fa517c8c450>

  File "/content/YOLOX/yolox/core/trainer.py", line 73, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x7fa517f6df80>
    └ <yolox.core.trainer.Trainer object at 0x7fa517c8c450>

  File "/content/YOLOX/yolox/core/trainer.py", line 155, in before_train
    self.prefetcher = DataPrefetcher(self.train_loader)
    │                 │              │    └ <yolox.data.dataloading.DataLoader object at 0x7fa514907f50>
    │                 │              └ <yolox.core.trainer.Trainer object at 0x7fa517c8c450>
    │                 └ <class 'yolox.data.data_prefetcher.DataPrefetcher'>
    └ <yolox.core.trainer.Trainer object at 0x7fa517c8c450>

  File "/content/YOLOX/yolox/data/data_prefetcher.py", line 21, in __init__
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x7fa51c1e9710>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fa514907890>

  File "/content/YOLOX/yolox/data/data_prefetcher.py", line 25, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │                │                             │    └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fa514907350>
    │                │                             └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fa514907890>
    │                └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fa514907890>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x7fa514907890>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7fa529bb17a0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fa514907350>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7fa515baa350>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7fa529bb18c0>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7fa514907350>

  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7fa624780290>
    └ <torch._utils.ExceptionWrapper object at 0x7fa515baa350>

  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
          │    │        └ 'Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/usr/local/lib/p...
          │    └ <class 'AssertionError'>
          └ <torch._utils.ExceptionWrapper object at 0x7fa515baa350>

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 110, in wrapper
    ret_val = getitem_fn(self, index)
  File "/content/YOLOX/yolox/data/datasets/mosaicdetection.py", line 93, in __getitem__
    img, _labels, _, img_id = self._dataset.pull_item(index)
  File "/content/YOLOX/yolox/data/datasets/coco.py", line 206, in pull_item
    img = self.load_resized_img(index)
  File "/content/YOLOX/yolox/data/datasets/coco.py", line 179, in load_resized_img
    img = self.load_image(index)
  File "/content/YOLOX/yolox/data/datasets/coco.py", line 194, in load_image
    assert img is not None
AssertionError

#####

Here's my nano.py info:

#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright (c) Megvii, Inc. and its affiliates.

import os

import torch.nn as nn

from yolox.exp import Exp as MyExp

class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.depth = 0.33
        self.width = 0.25
        self.input_size = (416, 416)
        self.mosaic_scale = (0.5, 1.5)
        self.random_size = (10, 20)
        self.test_size = (416, 416)
        self.exp_name = os.path.split(
            os.path.realpath(__file__))[1].split(".")[0]
        self.enable_mixup = False

        # Define yourself dataset path
        self.data_dir = "/content/YOLOX/test"
        self.train_ann = "/content/train/train_annotations.json"
        self.val_ann = "/content/validation/validation_annotations.json"

        self.num_classes = 4

        self.max_epoch = 100
        self.data_num_workers = 4
        self.eval_interval = 1

    def get_model(self, sublinear=False):
        def init_yolo(M):
            for m in M.modules():
                if isinstance(m, nn.BatchNorm2d):
                    m.eps = 1e-3
                    m.momentum = 0.03

        if "model" not in self.__dict__:
            from yolox.models import YOLOX, YOLOPAFPN, YOLOXHead
            in_channels = [256, 512, 1024]
            # NANO model use depthwise = True, which is main difference.
            backbone = YOLOPAFPN(self.depth,
                                 self.width,
                                 in_channels=in_channels,
                                 depthwise=True)
            head = YOLOXHead(self.num_classes,
                             self.width,
                             in_channels=in_channels,
                             depthwise=True)
            self.model = YOLOX(backbone, head)

        self.model.apply(init_yolo)
        self.model.head.initialize_biases(1e-2)
        return self.model

###

I have marked use_sample_image = False

###
import os

# 独自のデータを使用する場合は、パスを指定してください
# Please fill in the path if you want to use your own data
if use_sample_image:
    dataset_directory = 'YOLOX-Colaboratory-Training-Sample/02.annotation_data'
else:
    dataset_directory = '/content/YOLOX/test'

# 学習/検証データパス(train/validation data path)
train_directory = '/content/YOLOX/train'
validation_directory = '/content/YOLOX/validation'

# 学習データ格納ディレクトリ作成(Create training data storage directory)
os.makedirs(train_directory, exist_ok=True)
# 検証データ格納ディレクトリ作成(Create verification data storage directory)
os.makedirs(validation_directory, exist_ok=True)

###

Here's the voc2coco info:

!python voc2coco/voc2coco.py /content/YOLOX/train train/train_annotations.json
!python voc2coco/voc2coco.py /content/YOLOX/validation validation/validation_annotations.json

###

Here's the training data preparation:

!mkdir dataset
!mkdir dataset/images
!mkdir dataset/images/train2017
!mkdir dataset/images/val2017
!mkdir dataset/annotations

!cp -rf /content/YOLOX/train dataset/images/train2017
!cp -rf /content/YOLOX/validation dataset/images/val2017
!cp -rf train/train_annotations.json dataset/annotations
!cp -rf validation/validation_annotations.json dataset/annotations

I have not changed the .json locations only the input of the train and validation data.

Any help would be much appreciated!

Thank you!

**Comment by Kazuhito00** [comment]
Does the image file name contain a non-numeric name?
If so, I've improved notebook, so give it a try.

The correction points are as follows.
```
Pascal VOC形式 を MS COCO形式へ変換(Convert Pascal VOC format to MS COCO format)
```
```
!git clone https://github.com/Kazuhito00/convert_voc_to_coco.git
```
```
!python convert_voc_to_coco/convert_voc_to_coco.py \
    train train/train_annotations.json \
    --start_image_id=0
!python convert_voc_to_coco/convert_voc_to_coco.py \
    validation validation/validation_annotations.json \
    --start_image_id=10000000
```

**Comment by joshfox10** [comment]
I saw that correction, but unfortunately the filenames do not.  I suspect it is how my data directories are set up.  I had some confusion on the three parts: data directory, training, validation.  Is there a required directory structure?  
Thank you in advance for your help.

**Comment by Kazuhito00** [comment]
The samples in this repository assume that the image files are in "/content/dataset/images".
```
!mkdir dataset
!mkdir dataset/images
!mkdir dataset/images/train2017
!mkdir dataset/images/val2017
!mkdir dataset/annotations
```
nano.py
```
        # Define yourself dataset path
        self.data_dir = "/content/dataset/images"
```

--- 

You only changed the config file path and it doesn't seem to change the cp directory.

nano.py
```
    # Define yourself dataset path
    self.data_dir = "/content/YOLOX/test"
```
Store the image file below.
```
!mkdir YOLOX
!mkdir YOLOX/test
!mkdir YOLOX/test/train2017
!mkdir YOLOX/test/val2017
```

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.

**Comment by joshfox10** [comment]
> The samples in this repository assume that the image files are in "/content/dataset/images".
> 
> ```
> !mkdir dataset
> !mkdir dataset/images
> !mkdir dataset/images/train2017
> !mkdir dataset/images/val2017
> !mkdir dataset/annotations
> ```
> 
> nano.py
> 
> ```
>         # Define yourself dataset path
>         self.data_dir = "/content/dataset/images"
> ```
> 
> You only changed the config file path and it doesn't seem to change the cp directory.
> 
> nano.py
> 
> ```
>     # Define yourself dataset path
>     self.data_dir = "/content/YOLOX/test"
> ```
> 
> Store the image file below.
> 
> ```
> !mkdir YOLOX
> !mkdir YOLOX/test
> !mkdir YOLOX/test/train2017
> !mkdir YOLOX/test/val2017
> ```

This seemed to do the trick!  Thank you for your help!
